import type { SuggestionAdapter, ThreadMessage } from '@assistant-ui/react';

export type FollowUpSuggestion = {
  label: string;
  prompt: string;
};

const isCompleteAssistant = (message: ThreadMessage) =>
  message.role === 'assistant' &&
  (message.status?.type === 'complete' || !message.status);

const normalizeFollowUps = (raw: unknown): FollowUpSuggestion[] => {
  if (!Array.isArray(raw)) {
    return [];
  }

  const seen = new Set<string>();
  const unique: FollowUpSuggestion[] = [];
  for (const item of raw) {
    const label = typeof (item as any)?.label === 'string' ? (item as any).label.trim() : '';
    const prompt = typeof (item as any)?.prompt === 'string' ? (item as any).prompt.trim() : '';
    if (!label || !prompt || seen.has(prompt)) continue;
    seen.add(prompt);
    unique.push({ label, prompt });
    if (unique.length >= 4) break;
  }
  return unique;
};

/**
 * Follow-ups are generated by the chat agent and travel with each assistant
 * message under `metadata.custom.followUps` (set live by the stream adapter and
 * rehydrated from persisted history). We surface the ones attached to the most
 * recent completed assistant turn — no client-side heuristics.
 */
export const buildFollowUpSuggestions = (messages: readonly ThreadMessage[]): FollowUpSuggestion[] => {
  const lastAssistant = [...messages].reverse().find(isCompleteAssistant);
  if (!lastAssistant) {
    return [];
  }

  return normalizeFollowUps((lastAssistant.metadata?.custom as any)?.followUps);
};

export const createJobChatSuggestionAdapter = (): SuggestionAdapter => ({
  async generate({ messages }) {
    return buildFollowUpSuggestions(messages).map((item) => ({ prompt: item.prompt }));
  },
});
